name: Rust

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - name: Login
      run: cargo login ${{ secrets.CARGO_TOKEN }}
    - name: Publish
      run: cargo publish
